### ISSUE TITLE
Refactor code and user Redux?

### ISSUE THREAD

**Issue by JMStudiosJoe** [Opportunity-Hack-San-Jose-2017/Team3#14]
Would now be a good time to update the code base to use Redux? May want to have a google hangout chat about this but something to consider now that we have time.

**Comment by naderchehab** [comment]
👍

**Comment by JMStudiosJoe** [comment]
this is actually two issues, refactoring code and then adding redux. refactoring has been doing some in cleanup-reorganizing and will likely need further once redux is in but now that branch is done time  to add redux.
