### ISSUE TITLE
Secure login

### ISSUE THREAD

**Issue by naderchehab** [Opportunity-Hack-San-Jose-2017/Team3#15]
Use bcrypt to hash and salt passwords: https://www.abeautifulsite.net/hashing-passwords-with-nodejs-and-bcrypt

**Comment by JMStudiosJoe** [comment]
I saw something like this and yes we will need to add this. Where are the locations to add it? In lib/db.js in the signup and login but what about db schemas to store the passphrase properly?

**Comment by JMStudiosJoe** [comment]
added in branch bycrypt-integration.

**Comment by JMStudiosJoe** [comment]
do we need to secure it from the frontend or in a specific location or just using bycrypt in db.js when signing up and logging in is enough for now? @naderchehab

**Comment by naderchehab** [comment]
I think bcrypt does the job. 👍  If we find anything else we can open a new issue.
