### ISSUE TITLE
Password protect sensitive routes

### ISSUE THREAD

**Issue by naderchehab** [Opportunity-Hack-San-Jose-2017/Team3#17]
Use http://www.passportjs.org/ to password protect sensitive routes such as /users.

**Comment by JMStudiosJoe** [comment]
Great idea. Should we also think about what other paths as well?

**Comment by naderchehab** [comment]
any route that does user insert, update or even view will need this. We will need to have two kinds of accounts: admin accounts that can view/edit any user and user accounts that can only view/edit their own accounts but not any other account.

**Comment by naderchehab** [comment]
This PR handles this issue: https://github.com/Opportunity-Hack-San-Jose-2017/Team3/pull/31
