### ISSUE TITLE
Migrate react-facebook-login to passport-facebook

### ISSUE THREAD

**Issue by naderchehab** [Opportunity-Hack-San-Jose-2017/Team3#36]
https://github.com/jaredhanson/passport-facebook

**Comment by JMStudiosJoe** [comment]
We need to integrate this package and use it right in order to login with facebook? @naderchehab

**Comment by naderchehab** [comment]
Yes. Working on it today.

**Comment by naderchehab** [comment]
https://github.com/Opportunity-Hack-San-Jose-2017/Team3/pull/41
