### ISSUE TITLE
Facebook Login on Prod Heroku

### ISSUE THREAD

**Issue by JMStudiosJoe** [Opportunity-Hack-San-Jose-2017/Team3#8]
Facebook login button to work correctly on Heroku app when deployed.

**Comment by JMStudiosJoe** [comment]
also not working on development
<img width="1291" alt="screen shot 2017-11-03 at 9 31 06 am" src="https://user-images.githubusercontent.com/4028643/32402308-3d3e32b0-c0de-11e7-8871-292837028977.png">

**Comment by naderchehab** [comment]
Login is working now but:
1. You have to use https and not http:   https://givelight.herokuapp.com
2.There is some other issue on the profile page, probably some bad DB data. Will fix that before closing this issue.
